import "@/app/globals.css";
import AppTheme from "@/modules/shared/app-theme";
import { GlobalStyle } from "@/styles/globalStyles";
import { defaultTheme } from "@/styles/themes/default";
import type { Metadata } from "next";
import { Geist } from "next/font/google";

const openSans = Geist({
  variable: "--font-open-sans",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

type LayoutProps = {
  children: React.ReactNode;
  params: Promise<{
    locale: string;
  }>;
};

export default async function RootLayout({ children, params }: LayoutProps) {
  const { locale } = await params;

  return (
    <html lang={locale}>
      <body className={openSans.className}>
        <AppTheme theme={defaultTheme}>
          <GlobalStyle />
          {children}
        </AppTheme>
      </body>
    </html>
  );
}
